// Shared constants and default values
import type { WidgetAdvancedConfig } from './types';

export const MAX_FREE_WIDGETS = 1;

export const DEFAULT_WIDGET_CONFIG = {
  webhookRoute: 'general',
  poweredByText: 'Powered by Nexora',
  poweredByLink: process.env.NEXT_PUBLIC_APP_URL || 'https://nexora.app',
  primaryColor: '#854fff',
  secondaryColor: '#6b3fd4',
  backgroundColor: '#ffffff',
  fontColor: '#333333',
  position: 'right' as const,
};

export const APP_NAME = 'Nexora';

export const DEFAULT_ADVANCED_CONFIG: WidgetAdvancedConfig = {
  bubble: {
    borderRadiusStyle: 'circle',
    backgroundColor: '#854fff',
    customIconUrl: '',
    customIconSize: 60,
    customIconBorderRadius: 15,
    internalIconsColor: '#373434',
    size: 50,
    rightPosition: 20,
    bottomPosition: 20,
    autoOpen: false,
    openDelay: 0,
    animation: 'none',
    animationSpeed: 'normal',
    animateOnlyOnLoad: false,
  },
  tooltip: {
    display: true,
    hideOnMobile: true,
    message: 'Hello 👋 How can I help you?',
    backgroundColor: '#fffff0',
    textColor: '#1c1c1c',
    fontSize: 15,
  },
  window: {
    borderRadiusStyle: 'rounded',
    height: 600,
    width: 400,
    backgroundColor: '#f7f8fa',
    fontSize: 16,
    showScrollbar: true,
    showTitle: true,
    title: '',
    titleAvatarUrl: '',
    avatarSize: 40,
    avatarBorderRadius: 25,
    welcomeMessage: '',
    customErrorMessage: 'Something went wrong. Please try again.',
    starterPrompts: [],
    starterPromptFontSize: 13,
    messageBorderRadius: 8,
    renderHtml: false,
    clearOnReload: true,
    showBackToWelcome: true,
    showRefreshButton: true,
    showSendButton: true,
    sendButtonIcon: 'arrow-up',
    showTimestamps: false,
    timestampFormat: '12-hour',
    timestampColor: '#999999',
    timestampFontSize: 11,
    showSocialIcons: false,
    socialLinks: [],
    socialIconSize: 18,
    socialIconColor: '',
    shadowEnabled: false,
    shadowColor1: '#854fff',
    shadowColor2: '#6b3fd4',
    shadowBlur: 20,
    shadowSpread: 5,
    shadowAnimate: false,
    shadowAnimationSpeed: 3,
  },
  botMessage: {
    backgroundColor: '#f86839',
    textColor: '#fefefe',
    showAvatar: true,
    avatarUrl: '',
    showCopyIcon: false,
    showTypingIndicator: true,
    typingIndicatorColor: '',
  },
  userMessage: {
    backgroundColor: '#eeeeee',
    textColor: '#603005',
    showAvatar: true,
    avatarUrl: '',
  },
  inputField: {
    borderRadius: 5,
    placeholder: 'Type a message...',
    backgroundColor: '#ffffff',
    textColor: '#000000',
    sendButtonColor: '#854fff',
    sendButtonBorderRadius: 30,
    maxCharacters: 0,
    maxCharsWarning: 'You exceeded the character limit.',
    autoFocus: false,
    showEmojiPicker: false,
  },
  footer: {
    mode: 'content',
    text: 'Powered by',
    companyName: '',
    companyLink: '',
    textColor: '#303235',
    customHtml: '',
    showLogo: false,
    logoSource: 'brand',
    customLogoUrl: '',
    logoPosition: 'left',
    logoSize: 16,
  },
  advanced: {
    customCss: '',
    enableLanguageSelector: false,
    availableLanguages: ['en'],
    defaultLanguage: 'en',
    enableCustomCursor: false,
    cursorType: 'preset',
    presetCursor: 'pointer',
    customCursorUrl: '',
    enableColorTransitions: false,
    colorTransitions: {
      headerTransition: false,
      headerColor1: '#854fff',
      headerColor2: '#6b3fd4',
      toggleTransition: false,
      toggleColor1: '#854fff',
      toggleColor2: '#6b3fd4',
      userMessageTransition: false,
      userMessageColor1: '#854fff',
      userMessageColor2: '#6b3fd4',
      botMessageTransition: false,
      botMessageColor1: '#f86839',
      botMessageColor2: '#6b3fd4',
      transitionSpeed: 3,
    },
    enableFallingEffect: false,
    fallingEffect: {
      effectSource: 'brand',
      customImageUrl: '',
      emoji: '✨',
      particleCount: 15,
      fallSpeed: 'medium',
      particleSize: 20,
      showOnDesktop: true,
      showOnMobile: false,
    },
  },
  welcomePage: {
    welcomeButtonText: 'Send us a message',
    showWelcomeLogo: true,
    welcomeLogoSource: 'brand',
    welcomeCustomLogoUrl: '',
    welcomeLogoPosition: 'top-center',
    welcomeLogoSize: 60,
    welcomeLogoAnimation: 'none',
    welcomeButtonAnimation: 'none',
    welcomeBackgroundColor: '',
  },
};
